stages:
  - ingest

image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

ingest_francetravail_production:
  stage: ingest
  tags:
    - shell
  script:
    - python3 -m pipelines.ingest_francetravail
  only:
    - production