image: python:3.11

stages:
  - ingest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

ingest_francetravail_production:
  tags: shell
  stage: ingest
  script:
    - python -m pipelines.ingest_francetravail
  only:
    - production
